spring:
  application:
    name: product-service

---
spring:
  config:
    activate:
      on-profile: local
    import: "configserver:http://localhost:8888"

---
spring:
  config:
    activate:
      on-profile: docker
    import: "configserver:http://config-service:8888"

